site_name: (WIP) Bashor Lab

theme:
  name: material
  logo: './images/favicon.png'
  favicon: './images/favicon.png'
  menu: './images/favicon.png'

  palette: 
    scheme: slate
    primary: black

  features:
    # - header.autohide
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections

nav:
  - HOME: 'index.md'
  - PUBLICATIONS: 'publications.md'
  - PEOPLE: 'roster.md'
  - CONTACT: 'contact.md'
  - GitHub: 'https://github.com/cbashorlab'

extra_css:
  - assets/stylesheet.css
  - assets/animation.css

extra_javascript:
  - assets/script.js

markdown_extensions:
  - attr_list
  - md_in_html

# plugins: []  # remove search bar
